### ISSUE TITLE
Update BMI input units

### ISSUE THREAD

**Issue by madMatchstick** [NOAA-OWP/topmodel#18]
All input/output units are in `m/h` as commented in [source code](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/refs/original_code_c/tmod9502.c#L381).  Current BMI input units for `rain` (CSDMS: `atmosphere_water__liquid_equivalent_precipitation_rate`) and `ep` (CSDMS: `water_potential_evaporation_flux`) should be updated from 
```
static const char *input_var_units[INPUT_VAR_NAME_COUNT] = {
        "kg m-2",
        "m s-1"
};
```
in [bmi_topmodel.c](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/src/bmi_topmodel.c#L122) to,
```
static const char *input_var_units[INPUT_VAR_NAME_COUNT] = {
        "kg m-2/1000.0",
        "kg m-2/1000.0"
};
```

**Comment by peckhams** [comment]
The units string should not contain conversion constants, as I understand
it, because they will not be recognized by the unit conversion tools like
UDUNITs.  Multiplying by constants (if needed) should be done internally.
Best,
Scott

**Comment by SnowHydrology** [comment]
@madMatchstick To echo what Scott said, please do not add numerical conversion to the units. Additionally, neither of those conversions would produce m/h.

**Comment by madMatchstick** [comment]
@SnowHydrology @peckhams @lcunha0118 Agreed - conversion constants for var units does seem a bit off.  What is, then, the proper string that I'm after here? Just `m h-1`, yes?

**Comment by peckhams** [comment]
Just remove the constants, so "kg m-2/1000.0" becomes "kg m-2".
Best,
Scott

**Comment by stcui007** [comment]
Does bmi-cfe have similar issue?

**Comment by SnowHydrology** [comment]
@madMatchstick and @peckhams, if the model is expecting input precipitation in m/h, then its BMI specification should give 'm h-1' as the var_unit. It will be up to the model engine to make conversions.

**Comment by lcunha0118** [comment]
When I looked at this last week, I saw kg m-2, so I asked Jess to add kg m-2/1000 as a place hold so the group can discuss what would be the best approach. It seems that "atmosphere_water__liquid_equivalent_precipitation_rate" should be a volume and not a rate (????) and that is why we did not specify m/h directly. @peckhams , any comment on that? For example, in CFE atmosphere_water__liquid_equivalent_precipitation_rate units is kg m-2.

**Comment by lcunha0118** [comment]
Actually, m/h does not work since the unit is volume/dt... and dt is not necessarily hour.

**Comment by madMatchstick** [comment]
From https://csdms.colorado.edu/wiki/CSN_Searchable_List-Names, `atmosphere_water__domain_time_integral_of_rainfall_volume_flux` ?  Recall topmodel only considers precip as rain...

**Comment by SnowHydrology** [comment]
To confirm what @lcunha0118 said, my reading is that TOPMODEL expects precipitation to be given in the unit of m per timestep. This is trivial when the timestep is 1 h, but less so when it is not.
