### ISSUE TITLE
Topmodel function `expinf` doesn't give output.

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/topmodel#19]
Not sure if this block of code is ever activated in any testing, but the function call to `expinf` [here](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/src/topmodel.c#L190) doesn't actually do anything.
It looks like it is _intended_ to update the values of `df` and `cumf`, but since the function is *pass by value* these values are never modified on the caller's side.  This means that `rex` and ultimately `p` are using the undefined value of the uninitialized variable `df`.  This can have some unintended consequences.

The definition of the function [here](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/src/topmodel.c#L698) would need to be changed to

```C
extern void expinf(int irof, int it, int rint, double* df, double* cumf,
                   double dt,double xk0, double szm, double hf)
```
and then called by passing references the required update variables
```C
expinf(irof,it,rint,&df,&cumf,dt,xk0,szm,hf);
```

**Comment by lcunha0118** [comment]
@hellkite500  FYI we are not running topmodel with infiltration excess on. infex==0 for our runs, and therefore this function is not being called. However, if this is an issue, it should be fixed, because the user should have the option of running infiltration excess.
