### ISSUE TITLE
Integration Test Fails for Ubuntu-20.04

### ISSUE THREAD

**Issue by madMatchstick** [NOAA-OWP/topmodel#49]
`build-ngen` action fails for linux runner.  See job details [here](https://github.com/NOAA-OWP/topmodel/actions/runs/8836741968/job/24264015359). 

Possible related discussions(?)
1. build fails but on macos: [NOM issue#107](https://github.com/NOAA-OWP/noah-owp-modular/issues/107)
2. ngen ci fix: [merged pr#804](https://github.com/NOAA-OWP/ngen/pull/804/files)

**Comment by PhilMiller** [comment]
Ah, this is my fault. I updated the ngen CI jobs to Ubuntu 22.04, with GCC 11, and then later added warning flags

**Comment by PhilMiller** [comment]
Best solution, I think, would be to just move the topmodel (and other formulation) jobs to Ubuntu 22.04 as well. I don't think there's much reason to hang onto 20.04 in particular.

**Comment by madMatchstick** [comment]
@PhilMiller - Thanks for pointing this out! I'm rooting for `ubuntu-latest` vs. calling out specific versions.  Objections? -thx
